FROM python:2.7-jessie
MAINTAINER Andrew Dunai

RUN mkdir /home/isc

COPY ./requirements /home/isc/requirements

WORKDIR /home/isc

# Install requirements
RUN \
    python2.7 -m pip install -r ./requirements/test.txt

COPY ./.flake8 /home/isc
COPY ./.coveragerc /home/isc
COPY ./.coveralls.yml /home/isc
COPY ./pytest.ini /home/isc
COPY ./Makefile /home/isc
COPY ./isc /home/isc/isc

