version: '2.0'
services:
    app:
        image: isc-test
        build: .
        environment:
            RABBITMQ_HOST: amqp://guest:guest@rabbitmq:5672
            PYTHONUNBUFFERED: 0
        command: sh -c 'sleep 5 && py.test'
        links:
            - rabbitmq
    rabbitmq:
        image: rabbitmq
        logging:
            driver: "none"

