version: '2.0'
services:
    app:
        image: isc-test
        build: .
        environment:
            RABBITMQ_HOST: amqp://guest:guest@rabbitmq:5672
            PYTHONUNBUFFERED: 0
        command: sh -c 'sleep 5 && make test && flake8 && coveralls'
        links:
            - rabbitmq
        volumes:
            - ./.git:/home/isc/.git
    rabbitmq:
        image: rabbitmq
        logging:
            driver: "none"

